<?php

namespace App\Modules\Commerce\Services;

use App\Modules\Commerce\Models\Invoice;
use App\Modules\Tenancy\Models\Tenant;
use App\Support\Files\DocumentService;
use App\Support\Files\Enums\DocumentPurpose;
use App\Support\Files\Models\Document;
use App\Support\Files\StoreOptions;
use Barryvdh\DomPDF\Facade\Pdf;

/**
 * Renders an invoice to a PDF and records it as a document on the invoice.
 *
 * The file stays private and is streamed only through the access-controlled
 * download endpoint. What changes here is that a generated PDF is now a tracked
 * file like any other: it appears in the academy's library, counts toward
 * storage, and a re-render replaces the old one instead of leaving it behind.
 */
class InvoicePdfService
{
    public function __construct(private readonly DocumentService $documents) {}

    /** (Re)render + store the PDF, returning the document that holds it. */
    public function generate(Invoice $invoice): Document
    {
        $invoice->loadMissing(['order.items', 'order.user']);
        $tenant = Tenant::withoutGlobalScopes()->find($invoice->tenant_id);

        $pdf = Pdf::loadView('invoices.pdf', [
            'invoice' => $invoice,
            'order' => $invoice->order,
            'tenant' => $tenant,
            'buyer' => $invoice->order?->user,
        ])->setPaper('a4');

        $previous = $invoice->pdfDocument;

        $document = $this->documents->storeContents(
            $pdf->output(),
            "invoice-{$invoice->number}.pdf",
            DocumentPurpose::InvoicePdf,
            // The buyer owns the invoice, but the PDF is generated by the system
            // on the tenant's behalf; attributing it to the buyer keeps it out of
            // nobody's hands and lets them find it in their own files.
            new StoreOptions(ownerId: (int) ($invoice->order?->user_id ?? $invoice->user_id)),
        );

        $invoice->forceFill(['pdf_document_id' => $document->getKey()])->saveQuietly();

        // Only once the new PDF is safely recorded — a failed render must never
        // leave the invoice with no document at all.
        if ($previous !== null) {
            $this->documents->delete($previous);
        }

        return $document;
    }

    /** The stored document, rendering on first request if it is missing. */
    public function ensure(Invoice $invoice): Document
    {
        $document = $invoice->pdfDocument;

        return $document !== null && $document->exists()
            ? $document
            : $this->generate($invoice);
    }

    public function contents(Invoice $invoice): string
    {
        return $this->documents->contents($this->ensure($invoice));
    }
}
