@php
    /** @var \App\Modules\Commerce\Models\Invoice $invoice */
    $currency = $order->currency ?? 'EGP';
    $money = fn ($minor) => number_format(((int) $minor) / 100, 2).' '.$currency;
    $labels = [
        'course' => 'Course / كورس',
        'bundle' => 'Package / باقة',
        'wallet_topup' => 'Wallet top-up / شحن محفظة',
        'book' => 'Book / كتاب',
    ];
@endphp
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        * { font-family: DejaVu Sans, sans-serif; }
        body { font-size: 12px; color: #1a1a1a; margin: 0; padding: 28px; }
        .head { border-bottom: 2px solid #0D47A1; padding-bottom: 12px; margin-bottom: 18px; }
        .academy { font-size: 18px; font-weight: bold; color: #0D47A1; }
        .title { font-size: 22px; font-weight: bold; float: right; color: #0D47A1; }
        .meta td { padding: 2px 6px; vertical-align: top; }
        .meta .k { color: #666; }
        table.items { width: 100%; border-collapse: collapse; margin-top: 16px; }
        table.items th { background: #0D47A1; color: #fff; text-align: left; padding: 8px; font-size: 11px; }
        table.items td { border-bottom: 1px solid #e2e2e2; padding: 8px; }
        .total { margin-top: 14px; text-align: right; font-size: 15px; font-weight: bold; }
        .foot { margin-top: 30px; color: #888; font-size: 10px; border-top: 1px solid #e2e2e2; padding-top: 8px; }
    </style>
</head>
<body>
    <div class="head">
        <span class="title">INVOICE / فاتورة</span>
        <div class="academy">{{ $tenant?->name ?? 'Elameed Education' }}</div>
    </div>

    <table class="meta">
        <tr>
            <td class="k">Invoice No. / رقم الفاتورة</td>
            <td><strong>#{{ $invoice->number }}</strong></td>
            <td class="k">Date / التاريخ</td>
            <td>{{ optional($invoice->issued_at)->format('Y-m-d H:i') ?? now()->format('Y-m-d H:i') }}</td>
        </tr>
        <tr>
            <td class="k">Billed to / إلى</td>
            <td>{{ $buyer?->name ?? '—' }}</td>
            <td class="k">Phone / الهاتف</td>
            <td>{{ $buyer?->phone ?? '—' }}</td>
        </tr>
        <tr>
            <td class="k">Order / الطلب</td>
            <td colspan="3">{{ $order?->uuid ?? '—' }}</td>
        </tr>
    </table>

    <table class="items">
        <thead>
            <tr>
                <th>#</th>
                <th>Item / البند</th>
                <th>Type / النوع</th>
                <th style="text-align:right">Amount / المبلغ</th>
            </tr>
        </thead>
        <tbody>
            @foreach (($order?->items ?? []) as $i => $item)
                <tr>
                    <td>{{ $i + 1 }}</td>
                    <td>{{ $item->title ?: '—' }}</td>
                    <td>{{ $labels[$item->item_type] ?? $item->item_type }}</td>
                    <td style="text-align:right">{{ $money($item->price_minor) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="total">Total / الإجمالي: {{ $money($order?->total_minor ?? 0) }}</div>

    <div class="foot">
        Generated by Elameed Education · تم الإصدار عبر منصة العميد التعليمية.
        This is a system-generated invoice. هذه فاتورة صادرة آليًا.
    </div>
</body>
</html>
